# facebook:
#   verify: "rasa-bot"
#   secret: ${FACEBOOK_SECRET}
#   page-access-token: ${FACEBOOK_TOKEN}

# twilio:
#   account_sid: ${TWILIO_ACCT_SID}
#   auth_token: ${TWILIO_AUTH_TOKEN}
#   twilio_number: ${TWILIO_NUMBER}  # if using WhatsApp: "whatsapp:+440123456789"

rest:
